services:
  db:
    image: mysql:8
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db
    networks:
      - app-network

  app:
    build:
      context: app
    ports:
      - 8888:8888
    networks:
      - app-network

networks:
  app-network:
    driver: bridge